"""
main.py — TravelHUB Chatbot FastAPI Service
Runs on port 8001. Accepts chat queries from the Spring Boot backend,
performs RAG over ChromaDB, and returns answers generated by Groq LLM.
"""

import os
import threading
from datetime import datetime
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate

from data_sync import sync_all_data, load_vectorstore

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
AUTO_SYNC_INTERVAL_MINUTES = 5  # Fallback auto-sync interval


# ──────────────────────────────────────────────
# Background auto-sync timer (repeating every 5 min)
# ──────────────────────────────────────────────

def _schedule_auto_sync():
    """Runs sync_all_data() and then reschedules itself after 5 minutes."""
    print(f"[AutoSync] ⏰ Running scheduled sync at {datetime.now().strftime('%H:%M:%S')}")
    try:
        sync_all_data()
    except Exception as e:
        print(f"[AutoSync] ❌ Error during auto-sync: {e}")
    finally:
        # Reschedule regardless of success/failure
        timer = threading.Timer(AUTO_SYNC_INTERVAL_MINUTES * 60, _schedule_auto_sync)
        timer.daemon = True  # Won't block app shutdown
        timer.start()


# ──────────────────────────────────────────────
# Lifespan: startup & shutdown
# ──────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run startup tasks before the app accepts requests."""
    print("=" * 60)
    print("🚀 TravelHUB Chatbot Service starting up...")
    print(f"   Port     : 8001")
    print(f"   Auto-sync: every {AUTO_SYNC_INTERVAL_MINUTES} minutes")
    print(f"   Started  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # Initial sync on startup
    print("[Startup] 🔄 Performing initial data sync...")
    try:
        sync_all_data()
    except Exception as e:
        print(f"[Startup] ⚠️  Initial sync failed (chatbot will retry in {AUTO_SYNC_INTERVAL_MINUTES} min): {e}")

    # Start background auto-sync timer
    timer = threading.Timer(AUTO_SYNC_INTERVAL_MINUTES * 60, _schedule_auto_sync)
    timer.daemon = True
    timer.start()
    print(f"[Startup] ✅ Auto-sync scheduled every {AUTO_SYNC_INTERVAL_MINUTES} minutes as fallback")

    yield  # App is now running

    print("[Shutdown] TravelHUB Chatbot Service stopped.")


# ──────────────────────────────────────────────
# FastAPI app
# ──────────────────────────────────────────────

app = FastAPI(
    title="TravelHUB Chatbot Service",
    description="RAG-based AI travel assistant backed by Groq LLM",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────
# Request / Response models
# ──────────────────────────────────────────────

class ChatRequest(BaseModel):
    prompt: str


class ChatResponse(BaseModel):
    response: str


# ──────────────────────────────────────────────
# LLM + RAG chain builder
# ──────────────────────────────────────────────

SYSTEM_PROMPT = PromptTemplate(
    input_variables=["context", "question"],
    template="""You are TravelHUB's friendly and knowledgeable AI travel assistant for Sri Lanka.
You help tourists discover travel packages, hotels, and destinations available on TravelHUB.

STRICT RULES — you MUST follow these at all times:
1. Use ONLY the information provided in the context below. Do NOT invent, assume, or guess any details.
2. All prices in the context are in USD. Always present prices as USD (e.g. "$250 – $349 USD").
3. Never say "LKR" — all prices are in US Dollars.
4. If a price is missing from the context, say "Contact the agent/hotel for pricing" — never make up a number.
5. If the answer is not in the context, say "I don't have that information right now, but you can browse our full listings on TravelHUB."
6. Always be concise, accurate, and enthusiastic about Sri Lanka travel.

Context:
{context}

Tourist's Question: {question}

Answer:"""
)


def _build_qa_chain() -> RetrievalQA:
    """Build a fresh RetrievalQA chain from the current ChromaDB state."""
    vectorstore = load_vectorstore()
    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": 5},
    )
    llm = ChatGroq(
        api_key=GROQ_API_KEY,
        model_name="llama-3.1-8b-instant",
        temperature=0.3,
    )
    return RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        chain_type_kwargs={"prompt": SYSTEM_PROMPT},
        return_source_documents=False,
    )


# ──────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────

@app.get("/health")
async def health_check():
    """Health check — Spring Boot and frontend poll this."""
    return {
        "status": "ok",
        "service": "TravelHUB Chatbot",
        "timestamp": datetime.now().isoformat(),
    }


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Main chat endpoint.
    Spring Boot POST /chat → { "prompt": "..." }
    Returns           → { "response": "..." }
    """
    user_prompt = request.prompt.strip()
    if not user_prompt:
        return ChatResponse(response="Please type a question.")

    print(f"[Chat] 💬 User: {user_prompt[:100]}")

    try:
        qa_chain = _build_qa_chain()
        result = qa_chain.invoke({"query": user_prompt})
        answer = result.get("result", "I couldn't generate a response. Please try again.")
        print(f"[Chat] 🤖 Bot: {answer[:120]}...")
        return ChatResponse(response=answer)
    except Exception as e:
        print(f"[Chat] ❌ Error: {e}")
        return ChatResponse(
            response="I'm having trouble right now. Please try again in a moment."
        )


@app.post("/sync")
async def manual_sync():
    """
    Manual sync trigger — called by Spring Boot's ChatbotController /sync endpoint.
    Triggers a full data reload from the backend.
    """
    print(f"[Sync] 📡 Manual sync triggered at {datetime.now().strftime('%H:%M:%S')}")
    try:
        sync_all_data()
        return {"status": "Sync complete", "timestamp": datetime.now().isoformat()}
    except Exception as e:
        print(f"[Sync] ❌ Manual sync error: {e}")
        return {"status": f"Sync failed: {str(e)}", "timestamp": datetime.now().isoformat()}


@app.post("/notify-update")
async def notify_update(data: dict = None):
    """
    Real-time push endpoint called by Spring Boot's ChatbotSyncListener.
    Whenever a package or hotel is created/updated/approved, this is called
    immediately — no waiting for the 5-minute auto-sync.
    """
    print(f"[Notify] 🔔 Real-time update received: {data}")
    try:
        sync_all_data()
        return {
            "status": "Update synced immediately",
            "timestamp": datetime.now().isoformat(),
        }
    except Exception as e:
        print(f"[Notify] ❌ Sync after notification failed: {e}")
        return {
            "status": f"Sync failed: {str(e)}",
            "timestamp": datetime.now().isoformat(),
        }
